- design-tokens/aliases/base.yml
- design-tokens/components/buttons.yml
- design-tokens/components/font.yml
- design-tokens/components/inputs.yml
- package-lock.json
First pass at adding EP tokens to buttons
> Button tokens

- design-tokens/core/components/checkboxes.yml
- design-tokens/core/components/radio-buttons.yml
- design-tokens/theme-uplift.yml
- design-tokens/theme-uplift/components/checkboxes.yml
- design-tokens/theme-uplift/components/radio-buttons.yml
- package-lock.json
- package.json
- Resets some core values to what is currently in EP
- Adds the previous (new) values to the in-progress Uplift theme
> Reset some core values to what is in EP

- design-tokens/theme-soho-dark/components/font.yml
- design-tokens/theme-soho-high-contrast/components/font.yml
> font values added

- design-tokens/core.yml
- design-tokens/core/components/notifications.yml
- design-tokens/theme-soho-dark.yml
- design-tokens/theme-soho-dark/components/notifications.yml
- design-tokens/theme-soho-high-contrast.yml
- design-tokens/theme-soho-high-contrast/components/notifications.yml
Add notification (Banners) values
Issue #157
> Token extraction: Notifications

- design-tokens/core.yml
- design-tokens/core/components/pills.yml
- design-tokens/theme-soho-dark.yml
- design-tokens/theme-soho-dark/components/pills.yml
- design-tokens/theme-soho-high-contrast.yml
- design-tokens/theme-soho-high-contrast/components/pills.yml
Adds pill token values (badges/tags/alerts)
Issue #157
> Token Extraction: Pills

- design-tokens/core/components/radio-buttons.yml
> fixed old radio checked var

- design-tokens/theme-soho-dark/components/buttons.yml
- design-tokens/theme-soho-dark/components/notifications.yml
change token type to "style" for inherit. also adds missing values for some button tokens
related to #158
> Fix color types

- design-tokens/theme-soho-high-contrast/components/radio-buttons.yml
Fixes a few wrong values in the HC radio button tokens
related to #158
> fixing wrong values in hc radio buttons

- design-tokens/core/components/radio-buttons.yml
fixes the Theo conversion for transparent values.
related to #158
> changed color to style on radio-bg-color

- design-tokens/core/core.alias.yml
I guess Source Sans Pro should be a default font, shouldn't it?
> Added Source Sans Pro as a default font to design tokens.

- .github/CODEOWNERS
- scripts/node/generate-tokens.js
- scripts/node/utilities/tokens/xml.template
Added basic xml format for distributing tokens.
https://github.com/infor-design/design-system/issues/49
1. `npm run build:tokens`
1. Verify the xml format in the `dist/` file
> Added a basic xml format for tokens

- design-tokens/props/button.json
- design-tokens/props/checkbox.json
- design-tokens/props/list.json
- design-tokens/props/radio-button.json
- design-tokens/theme-soho/theme.json
- design-tokens/theme-uplift/theme.json
Finalize tokens to fix visual regressions in CSS.
Relates to infor-design/css#179
Pull and `npm run build:tokens` and make sure there are no errors.
> Updates tokens to fix visual regressions in CSS

- .travis.yml
- package.json
- scripts/node/generate-font.js
- scripts/node/generate-icons.js
- scripts/node/generate-tokens.js
Add pull request CI build checking for error detection.
#226 
1. Check the build info for this PR
> Add CI build checks

- design-tokens/props/button.json
- design-tokens/props/checkbox.json
- design-tokens/props/dropdown.json
- design-tokens/props/input.json
- design-tokens/theme-soho/theme.json
- design-tokens/theme-uplift/props/button.json
- design-tokens/theme-uplift/props/input.json
- design-tokens/theme-uplift/theme.json
Update the property string names to not have dashes and cause confusion with token naming.
n/a
1. Make sure the build is good
> Convert dashed token property names to a hierarchy

- design-tokens/theme-soho/variants/contrast/theme.json
Updating status colors to match the values in Sketch file.
> Update Contrast theme.json

- design-tokens/theme-soho/variants/contrast/props/checkbox.json
- design-tokens/theme-soho/variants/dark/props/dropdown.json
> Adds missing token values

- design-tokens/theme-uplift/theme.json
Updated type sizes for md, ld, xl, added line heights for sm to xl, and added a "light" font weight.
Closes #262
> Updated type sizes, added new line heights, and added a new font weight

- scripts/node/build-icons.js
We needed to clean the sketch file layers names for any inconsistent artifacts.
#291 
1. Create a layer name in sketch with whitespace and underscores
1. `npm run build:tokens`
1. Verify svg file name in corresponding `dist/` has dashes only.
> 291 - Added sanitize fn for icon naming [v2.2.x]

- design-tokens/props/header.json
- design-tokens/theme-soho/variants/contrast/props/header.json
- design-tokens/theme-soho/variants/dark/props/header.json
There was a need to add some context for the header, so we are starting with the primary background token.
#283 
1. Design-system
1. `npm run build:tokens`
1. Compare the values of the `dist/` files to the corresponding  `$header-bg-color` values in the config/theme files fo the Enterprise codebase.
1. Enterprise
1. `npm link` ids-identity into Enterprise
1. Then in Enterprise, build/start the demo app
1. Switch the themes and inspect/compare the header color to what is on latest
> 283 - Added a header primary background token [v2.2.x]

- design-tokens/props/list.json
- design-tokens/theme-soho/variants/contrast/props/list.json
- design-tokens/theme-soho/variants/dark/props/list.json
- design-tokens/theme-uplift/props/list.json
- package-lock.json
Updates existing theme-soho default color to match existing color, adds dark and contrast variant tokens, and theme-uplift prop override.
Closes #286
`npm run build:tokens`
> Adds token for list divider border

- design-tokens/theme-soho/theme.json
- design-tokens/theme-uplift/theme.json
Adds a medium font wait, and bumps uplift theme bold up to `800`.
n/a
n/a
> Adds medium font weight [v2.2.x]

- .release-it.json
- scripts/before-start.sh
Safety first! 👷 
n/a
```
~/P/i/design-system on before-release
$ unset DOCS_API_KEY
~/P/i/design-system on before-release
$ ./scripts/before-start.sh
ERROR: DOCS_API_KEY is unset and required for deploy
```
> Adds env var check before release starts [v2.2.x]

- blueprints/README.md
A "blueprint" is like an RFC, where for "substantial" changes, you draft architecture and requirements, then conduct a comment period before introducing any of the major changes.
n/a
Read through readme to see if the process makes sense
> Adds "Blueprint" process for documenting substantial changes

- sketch/README.md
Added a lot more guidelines to the readme for the Uplift icon set, including naming conventions, categories, and basic design guidelines.
n/a
n/a
> Updated the readme on icons guidelines

- announcements.json
- package-lock.json
- package.json
- scripts/node/postinstall.js
Some refactoring and tweaks to the postinstall announcements.
#309 
1. `npm prune && npm i`
1. Make sure the announcements still show
1. Test updating in another repo like
- enterprise
- css
> Using the semver module instead

- sketch/README.md
Updated Sketch Readme to include guidelines on App Icons
n/a
n/a
> Updated Sketch Readme to include guidelines on App Icons

- design-tokens/props/notifications.json
Migrate some of the notification colors over to the tokens.
https://github.com/infor-design/enterprise/issues/1857
https://github.com/infor-design/enterprise/issues/1865
1. Make sure tests pass
1. If you want the full monty, you can `npm link` this branch into the corresponding enterprise branch (https://github.com/infor-design/enterprise/pull/1869) and follow the steps on the PR.
> Added notification tokens

- design-tokens/theme-soho/variants/contrast/props/button.json
Updated values for disabled button in high contrast.
https://github.com/infor-design/design-system/pull/361
> 361 - Updated values for disabled button in high contrast

- design-tokens/theme-uplift/theme.json
- design-tokens/theme-uplift/variants/dark/props/body.json
- design-tokens/theme-uplift/variants/dark/props/button.json
- design-tokens/theme-uplift/variants/dark/props/checkbox.json
- design-tokens/theme-uplift/variants/dark/props/input.json
- design-tokens/theme-uplift/variants/dark/props/link.json
- design-tokens/theme-uplift/variants/dark/props/list.json
- design-tokens/theme-uplift/variants/dark/props/notifications.json
- design-tokens/theme-uplift/variants/dark/props/radio-button.json
- design-tokens/theme-uplift/variants/dark/theme-uplift-dark.config.json
- design-tokens/theme-uplift/variants/dark/theme.json
Add uplift dark variant.
#299 
> Add uplift dark variant

- design-tokens/metadata.json
- package-lock.json
- package.json
- scripts/node/build-meta.js
- scripts/node/build.js
Adding a tokens metadata file will give a bit of context as to what themes we have available at a code/consumption level.
#374 
1. `npm run build`
- verify that `dist/` includes the `metadata.json` file
1. `npm pack`
- verify that `dist/` includes the `metadata.json` file
> 374 - Add a theme metadata file in the tokens directory

- .release-it.json
- scripts/before-stage.sh
Adds back old var check script that never got merged into master.
Previous PR: #307 
Do a release?
> Add env var check before release

- announcements.json
- design-tokens/theme-soho/theme.json
- design-tokens/theme-uplift/theme.json
- docs/CHANGELOG.md
Adds new type hierarchy in subtle and vibrant themes
closes #427 
- npm run build
- check dist folder and make sure tokens compiled properly.
> Add new type sizes

- design-tokens/props/button.json
- design-tokens/props/dropdown.json
- design-tokens/props/form.json
- design-tokens/props/input.json
- design-tokens/props/label.json
- design-tokens/props/textarea.json
- design-tokens/theme-uplift/props/button.json
- design-tokens/theme-uplift/props/dropdown.json
- design-tokens/theme-uplift/props/input.json
- design-tokens/theme-uplift/props/label.json
- design-tokens/theme-uplift/props/textarea.json
- docs/CHANGELOG.md
- package.json
Added new set of compact and normal tokens for field heights and label margins. And a few small fixes.
#3249 
Will provide a link to follow that will be QA'd so will merge and do an EP PR.
> 3249 - Adds new tokens for form sizes

- package.json
Bump release-it version to the latest improvements from the source repo.  Looks like they got new maintainers.
> Bump release-it version.

- Makefile
- cd/Dockerfile
- package-lock.json
- package.json
https://jira.infor.com/browse/HLO-275
> Docker file path fix, bump versions in run.js, npm-cli-login version bump.

- .gitignore
- Makefile
- cd/run.sh
- release-it.json
Minor fixes.  Pass correct variable to changelog script.  Remove npm cli login and use token instead.
https://jira.infor.com/browse/HLO-274
We need to run the build.  --dry-run shows no errors.
> Minor fixes.

- .npmrc
- Makefile
- README.md
- cd/k8s/job.yaml
- cd/k8s/task-definition.yaml
- cd/run.sh
Explain the details for making this change. What existing problem does the pull request solve?
Minor fixes. Remove unused env vars, fix git related warnings, job template updates.
Related github/jira issue (required):
https://jira.infor.com/browse/HLO-274
Steps necessary to review your pull request (required):
Run the jenkins job, with --dry-run flag.
> CI related updates, fixes and cleanup.

- design-tokens/theme-new/variants/dark/theme.json
- docs/CHANGELOG.md
The header colors in dark mode are not correct
Fix for 6446 but needs to be added to the package. json and released
- build then copy the dist over
- node_modules/ids-identity
- http://localhost:4000/components/personalize/example-color-theme-api.html?theme=new&mode=dark
> 6446 - Fix dark mode tokens

- design-tokens/theme-classic/variants/dark/theme.json
- docs/CHANGELOG.md
> Fix classic theme too

- .gitignore
- cd/k8s/job.yaml
- cd/k8s/secrets.sh
- cd/k8s/secrets/docs-api-key.yaml
- cd/k8s/secrets/github-acccess-token.yaml
- cd/k8s/secrets/npm-token.yaml
- cd/k8s/task-definition.yaml
- cd/run.sh
Removing sensitive env vars from k8s manifests and jenkins job.
There is no Jira, this is something I borrowed from my work on enterprise.
We need to run the Jenkins job on next release. All tests passed, and test dry-runs went fine.
> Remove secure env vars from manifests. Some cleanup.

- Makefile
- README.md
- cd/.gitconfig
- cd/Dockerfile
- cd/k8s/README.md
- cd/k8s/job.yaml
- cd/k8s/task-definition.yaml
- cd/run.sh
https://jira.infor.com/browse/HLO-295
> fix: .gitconfig mount, releaseit flags

- .release-it.json
- cd/Makefile
- cd/form/data.json
- cd/form/schema.json
- cd/form/uischema.json
- cd/k8s/job.yaml
- cd/run.sh
- scripts/node/map.json
- remove after release hooks
- update job manifest
- update Makefile
- remove unused export from map.json
- minor cleanup
Random improvements to the ci/cd scripts
> cd improvements
