infor-design/design-system

- design-tokens/core.yml
- design-tokens/core/components/colors.yml
Split the core brand colors into specific categories and rename the file to not be too specific.
Closes #135 
- Review the file hierarchy and `core/colors.yml` has 2 token categories in it (colors-brand, colors-status)
- Make sure it builds without errors
**Note** This may need to change how the token values are "connected" on the website @jmacaluso711
> Closes #135 Recategorize/rename brand color tokens

- scripts/node/generate-tokens.js
Need to have [theo](https://github.com/salesforce-ux/theo) convert colors to hex instead of `rgba()`
n/a
1. npm run build
1. Check the `dist/` token files for hex codes instead of `rgba()`
> Have theo convert colors to hex codes

- package.json
It's necessary to have the ES Module format when you build an app with CSS in JS such as Emotion. This way it's possible to use all themes in JS.
> Added ES Modules as a format for design tokens.

- package.json
- scripts/deploy-assets.sh
Deploys the dist token files to the Docs API so that the latest deployed version can be pulled into the website.
This script takes `dist/tokens`, zips it up, and publishes using the standard docs API mechanism we've developed.
Relates to https://github.com/infor-design/website/pull/635
1. Pull branch
1. Make sure `DOCS_API_KEY` environment variable is set in your current shell
2. From root, run `npm run deploy:stage`
3. You should see the script zipping, uploading, and receive a success message.
> Deploy tokens to docs API

- scripts/node/generate-tokens.js
- scripts/node/utilities/tokens/simple.json.template
Create a clean, flat json structure for the IDS website to use when rendering token data.
https://github.com/infor-design/website/issues/672
1. Run `npm run build:tokens` in the `design-system` repo (on this branch)
1. View the `dist/tokens/web/theme-*.simple.json` files
*e.g.*
```
[{
"name": "color-base-amber-10",
"value": "#fbe9bf",
"category": "color",
"original": {
"value": "#fbe9bf"
}
},
{
"name": "color-base-amber-20",
"value": "#f8e09c",
"category": "color",
"original": {
"value": "#f8e09c"
}
}]
```
> Create a new token format for IDS website use

- design-tokens/theme-soho/variants/dark/theme-soho-dark.config.json
- design-tokens/theme-soho/variants/dark/theme.json
Fix copy error on the dark theme config.
#235 
- Make sure the dark theme `$theme-color-brand-primary-base` color is the equivalent of `theme.color.palette.azure.60.value`
> 235 - Fix for wrong import uri in the dark theme config

- design-tokens/props/button.json
- design-tokens/props/checkbox.json
- design-tokens/theme-soho/variants/contrast/props/button.json
- design-tokens/theme-soho/variants/contrast/theme.json
- design-tokens/theme-soho/variants/dark/props/body.json
- design-tokens/theme-soho/variants/dark/props/checkbox.json
- package-lock.json
We were still noticing some color oddities post-2.0 release.
https://github.com/infor-design/enterprise/issues/1249
1. `npm run build`
1. `npm link` this branch
1. In enterprise, `npm link ids-identity`
1. Run *ids-enterprise* locally and compare the kitchen sink to the `v4.12.0` components:
**Additional Context**
Once this patch is released, have @clepore update the corresponding *ids-enterprise* branch and create a pull request into it's `4.13.x` branch (NOT `master`).
> 1249 - Fix some more theme color issues

- design-tokens/theme-soho/theme.json
Fixes #245
1. Make sure the original themes use the correct font family of "helvetica, arial, san-serif"
- soho theme
- soho dark theme
- soho high contrast theme
> Front - Restore the font to its previous entity

- design-tokens/props/checkbox.json
- package-lock.json
The disabled checked checkbox background is too dark and should be `graphite30`. 
n/a
Compare [v4.13.0-rc.0 checkboxes](http://4130-rc0-enterprise.demo.design.infor.com/components/checkboxes/example-index.html) to [v4.11.0 checkboxes]( https://design.infor.com/code/ids-enterprise/4.11.0/demo/components/checkboxes/example-index)
> Update checkbox token disabled color to be lighter

- .release-it.json
- scripts/github-changelog.sh
This is a little bit sketchy but covers for potential edge cases. Adds a `changelogCommand` which uses the same `git` command as `release-it` does to generate the change log but prepends it with some copy. The sketch part comes with the `beforeChangelogCommand`. `release-it` doesn't provide access to `${version}` within `changelogCommand` but does to `beforeChangelogCommand`, so I'm writing the version to a temp file that `changelogCommand` can read.
This allows us to directly link to the IDS asset download in the copy, which is a really nice bonus and worth the weirdness. If for some reason, the temp file can't be found, I have a fallback case. The script then removes the temp file when …
> Adds changelog command to prepend copy

- design-tokens/theme-soho/variants/contrast/theme.json
@kayiuho noticed that she updated the high contrast alert `danger` and `warning` color values incorrectly in https://github.com/infor-design/design-system/pull/255. The only color she wanted to actually update was `success`
n/a
- Design review to compare to sketch file
> High contrast theme reverse some previous alert color changes

- scripts/deploy-assets.sh
- scripts/package-release.sh
Gives more control over folder structure of asset release. Standardizes by using single script for both the Github asset release and the assets deployed to docs API.
> Standardize asset release

- design-tokens/theme-soho/variants/contrast/theme-soho-contrast.config.json
- design-tokens/theme-soho/variants/dark/theme-soho-dark.config.json
- design-tokens/theme-uplift/theme-uplift.config.json
- package-lock.json
- package.json
Uses `style-dictionary@2.7.0` feature https://github.com/amzn/style-dictionary/pull/227 to remove collision errors.
Relates to https://github.com/amzn/style-dictionary/issues/239
> Use include and source to override colors in variants

- design-tokens/props/body.json
- design-tokens/props/button.json
- design-tokens/props/checkbox.json
- design-tokens/props/dropdown.json
- design-tokens/props/icon.json
- design-tokens/props/input.json
- design-tokens/props/label.json
- design-tokens/props/link.json
- design-tokens/props/list.json
- design-tokens/props/radio-button.json
- design-tokens/theme-soho/theme.json
- design-tokens/theme-uplift/color-palette.json
- design-tokens/theme-uplift/props/input.json
- design-tokens/theme-uplift/theme.json
- scripts/node/build-icons.js
Added additional values to the Uplift color palette to match the SoHo color palette of 8 hues and 10 variations.
Closes #261 
n/a
---
*Note this is a fixed PR for https://github.com/infor-design/design-system/pull/289*
> Updating Uplift colors 

- package.json
- scripts/node/build.js
The previous addition to icons had the built `dist/` structure to be a bit inconsistent, leaving tokens as its own "entity" almost.
n/a
1. `npm run build`
⚠️ Breaking change ⚠️
>  Dist - Update build paths for theme consistency

- package.json
- scripts/node/build.js
We originally set `master` branch up to be `v3.0` but realized we might need some more `v2` work, so it needs to be backwards compatible.
n/a
- Test for `v2`
1. `npm run build:tokens`
2. See that the `dist/` has tokens in root `/`
- Test for `v3`
1. Temporarily change the package.json version to `3.0.0` (as long as first digit `> 2`)
2. `npm run build:tokens`
3. See that the tokens are now in their right `dist/theme-{theme}` hierarchy
> v2 and v3 token compatibility

- scripts/node/build-icons.js
SVGO automatically uses a self-close tag for svgs. For once IE is giving a useful warning about sticking to HTML5 standards and using closing tags for non-void HTML elements ([referenced here](https://stackoverflow.com/questions/28948210/how-to-avoid-html1500-tag-cannot-be-self-closing-warning-in-ie-when-using-embedd)
#312 
1. 'npm run build:icons'
1. View `dist/` of any svg file and make sure `<path ...></path>` is closed.
> 312 - HTML5 standards don't allow self-closing tags

- scripts/node/build.js
Need to support deprecated v2 paths for tokens in v3.
Closes #321
1. `npm run build:tokens` 
- and see tokens in root and under themes.
1. `npm run build` 
- and see tokens in root and under themes.
1. `npm run build:icons` 
- and see no errors
1. `npm run build:fonts` 
- and see no errors
> 321 - Temp copy fn to support deprecated v2 token paths

- design-tokens/theme-soho/theme.json
The font sizes depicted in the current tokens do not represent what exists in the Enterprise Soho theme.
#295 
1. build and `npm link` ids-identity
1. `npm link` ids-identity in Enterprise and then checkout the [associated branch](https://github.com/infor-design/enterprise/pull/1751) and run local enterprise to hopefully not see changes.
> 295 - Update soho theme to match current font sizes

- design-tokens/theme-soho/color-palette.json
Updating soho theme color palette Ruby10 HEX from #f4bcbc to #f6caca.
While working on a solve for #294 , we need a slightly lighter value for Ruby10 in order to produce the contrast needed to pass AA accessibility standards.
- #294
- Closes https://github.com/infor-design/enterprise/issues/1857
- Closes https://github.com/infor-design/enterprise/issues/1865
n/a
> Updating Theme Soho Color Palette Ruby10

- design-tokens/props/button.json
- design-tokens/theme-soho/variants/contrast/props/button.json
- design-tokens/theme-soho/variants/dark/props/button.json
- design-tokens/theme-uplift/props/button.json
Uses different colors and moves away from using opacity on buttons.
Closes #354, enables https://github.com/infor-design/enterprise/issues/1914
1. Make sure `npm run build` doesn't error.
1. Design-system repo:
1. Run `npm run build`
1. Run `npm link`
1. Enterprise repo:
1. Checkout branch `1914-remove-btn-opacity`
1. Run `npm i`
1. Run `npm link ids-identity`
1. Run `npm start`
1. Compare the following links:
| Localhost | v4.17.1 |
| --------- | ------- |
| [Light Theme](http://localhost:4000/) | [Light Theme](https://4171-enterprise.demo.design.infor.com) |
| [Dark …
> Uses lighter value to avoid using opacity

- package-lock.json
- package.json
Moves `log-symbols` from `devDependency` to `dependency` to work with `yarn`.
n/a
n/a
> Fix log-symbols dependency [2.6.x]

- design-tokens/theme-uplift/props/input.json
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR increases the difference in font color between an input field's placeholder text and actual text.
**Related github/jira issue (required):**
- Originally reported in infor-design/enterprise#2528
- Closes #393
**Steps necessary to review your pull request (required):**
TBD
**Additional Context**
This PR supersedes #394, which was committed against `master`, whereas this PR will be pushed to `2.6.x`
> Change Uplift Light's input placeholder color to be lighter [v2.6.x]

- design-tokens/theme-uplift/props/input.json
- design-tokens/theme-uplift/variants/contrast/props/button.json
- design-tokens/theme-uplift/variants/contrast/props/input.json
- design-tokens/theme-uplift/variants/contrast/theme.json
- design-tokens/theme-uplift/variants/dark/props/input.json
This PR adds some more token changes that affect Uplift Contrast:
- Brightens colors for Uplift Contrast disabled button styles
- Makes Uplift Contrast standard input fields white instead of transparent
- Dims colors used on Uplift Contrast/Dark disabled input fields (fades it into background)
- Brightens background color on Uplift Contrast readonly input fields
Closes #404
> 404 - more color changes

- design-tokens/theme-uplift/variants/dark/props/input.json
This PR brightens up the color of the Input field's placeholder text on the Uplift Dark theme.
Closes #404
Related to infor-design/enterprise#2708
> Brighten placeholder color on Uplift Dark

- cd/k8s/job.yaml
- cd/k8s/task-definition.yaml
Explain the details for making this change. What existing problem does the pull request solve?
Updates to kubernetes and argo manifests.
Related github/jira issue (required):
https://jira.infor.com/browse/HLO-274
Steps necessary to review your pull request (required):
We need to run the build. --dry-run shows no errors.
> Update kubernetes and argo manifests.

- design-tokens/theme-classic/theme.json
- design-tokens/theme-new/theme.json
Font sizes in our new theme do not match Infor Design Typography page, changing the existing font sizes might cause unknown effects, so I would like to add a new font size until we fully migrate to webcomponent some time in the future: 
add xxs to have font size 12 pixels for us to match product design with infor design system.
use class="font-size-xss" in div or span, font size should be 12 pixels if using theme new css.
> add xxs font size to theme css
